# Generated by Django 2.2.5 on 2019-09-02 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='FirstName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='LastName',
        ),
    ]
